[package]
name = "cdn"
version = "3.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10" }
tokio = { version = "0.2", features = ["full"] }
zip = "0.6.3"
log = "0.4"
chrono = "0.4"
