name: Rust

on:
  push:
    branches: [ 3.0.0-dev ]
  pull_request:
    branches: [ 3.0.0-dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-${{ matrix.backend }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Install dependencies
      run: sudo apt-get install -y build-essential cmake git libgit2-dev clang zlib1g-dev pkg-config llvm
     
    - name: Build project
      run: cargo build --locked --release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: epic-linux-x86_64
        path: ./target/release/epic
        retention-days: 5
